baseURL = "https://rosareven.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "I Forgot How I Did It"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I Forgot How I Did It"
author = "Rosareven"
#copyright = "2020-2021"
description = "So I'm writing everything down here"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/tinakhng/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/rosareven"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "mastodon"
url = "https://mastodon.gamedev.place/@rosareven"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:dev@rovingamer.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  # [[menu.main]]
  # name = "About"
  # weight = 300
  # identifier = "about"
  # url = "/about/"

  # [[menu.main]]
  # name = "Contact"
  # weight = 400
  # identifier = "contact"
  # url = "/contact/"
